### PR TITLE
Added React App

### PR DESCRIPTION
**Pull request by LI0131**

### CODE REVIEW

**Comment by LI0131** [comment]
Let's work on getting the current html app set up on this branch before we merge it with master

**Comment by alecaines** [comment]
Sorry, I only just saw this. I migrated what we had previously to an
angular-based front end on Monday. I'll try and translate that to React
over the next two days before I head off to New York.

**Comment by alecaines** [comment]
I'll push what I have to a separate branch so that you can look at it. It's
all of the same content, but instead of it begin vanilla html, it's built
on an angular app.

**Comment by LI0131** [comment]
You can just force push over what I’ve got on here if you want. Haha no need to translate

**Comment by alecaines** [comment]
I tried pushing to AddReactApp, but git wasn't able to find the branch. Do you know why that might be?

**Pull request merged**
